# Generated by Django 5.2.17 on 2026-09-14 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_education_ended_at_alter_education_started_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='description',
        ),
    ]
