# Generated by Django 5.2.17 on 2026-09-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_education_hobby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='description',
        ),
        migrations.AlterField(
            model_name='education',
            name='started_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
