# Generated by Django 5.2.17 on 2026-09-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_hobby_description_alter_education_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='ended_at',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='started_at',
            field=models.PositiveBigIntegerField(),
        ),
    ]
